# theme: jekyll-theme-minimal

# Site settings
title: BHA5 Japan
email: 
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bha5.club.org" # the base hostname & protocol for your site
twitter_username: ""
github_username: ""

# Plugins
safe: false

# Build settings
markdown: kramdown
